<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_First checkkk</name>
   <tag></tag>
   <elementGuidId>602ea2cc-a995-4a93-8a31-eb5fdfa9bf96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-black-a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-all']/div/div/div/div[2]/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ac52c43-ce57-4c4c-b6b7-d70fa08d02ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-black-a</value>
      <webElementGuid>0f1f071f-0dfb-45bd-b43a-464e5866ce03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First checkkk</value>
      <webElementGuid>71357f5d-28f9-4c14-91db-3282dbf96030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-all&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;primary-table m-3&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table mb-0&quot;]/tbody[@class=&quot;ng-star-inserted&quot;]/tr[@class=&quot;c-pointer ng-star-inserted&quot;]/td[@class=&quot;fs12 op-54 pl-4 fw-600&quot;]/a[@class=&quot;text-black-a&quot;]</value>
      <webElementGuid>25de4467-ef45-49b8-9a61-7b5acf88240b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-all']/div/div/div/div[2]/table/tbody/tr/td/a</value>
      <webElementGuid>e22a383a-af94-4ba6-846f-ef3fdc8346d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'First checkkk')]</value>
      <webElementGuid>28a1b986-5d16-4f3f-8fca-4d84816353a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::a[1]</value>
      <webElementGuid>162f1cde-991f-4ca3-8337-8d315ad9e996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::a[1]</value>
      <webElementGuid>fb40234b-537c-4d75-a5b5-3a8f3de43a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIL'])[1]/preceding::a[1]</value>
      <webElementGuid>d91a372c-e9f6-4210-878c-95a441ad9d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FirstCheck@yopmail.com'])[1]/preceding::a[1]</value>
      <webElementGuid>1ce9bc30-c250-4401-b46e-936513237f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='First checkkk']/parent::*</value>
      <webElementGuid>4253906b-9899-4719-a5f8-004f0e31afd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>91530856-ba75-43b3-ba1f-a5a72f50f7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'First checkkk' or . = 'First checkkk')]</value>
      <webElementGuid>a541d53f-414c-45a3-955c-7d02ac24b6e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
