<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Benedicta Company Name</name>
   <tag></tag>
   <elementGuidId>b800a346-eede-4e71-865a-8c315ae79a78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.dropdown-toggle.w-100.primary-drop.border-0.d-flex.align-items-center.p-0.show</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6217458a-8098-4227-8249-75e4f850b369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5dcfd253-96f8-4199-8160-ae492d8d710e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>bf9752d5-59f9-42e2-9673-e351afb5fcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>998b9ebd-b7a3-473f-973d-c5f76423af66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary dropdown-toggle w-100 primary-drop border-0 d-flex align-items-center p-0 show</value>
      <webElementGuid>9543afd2-287c-4032-a181-fe06a93c0f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Benedicta Company Name</value>
      <webElementGuid>8199e5ff-17f5-45b4-87c7-f41f35da0cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-app-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;admin-layout&quot;]/app-header[1]/header[@class=&quot;primary-header&quot;]/nav[@class=&quot;head-bar fixed-top&quot;]/div[@class=&quot;row justify-content-center align-items-center&quot;]/div[@class=&quot;col-6 col-md-2 col-md-4 col-lg-3 col-xl-2 d-flex align-items-center justify-content-end&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;profile-info d-flex align-items-center&quot;]/div[@class=&quot;dropdown px-2&quot;]/button[@class=&quot;btn btn-secondary dropdown-toggle w-100 primary-drop border-0 d-flex align-items-center p-0 show&quot;]</value>
      <webElementGuid>fd96bfd5-b374-4c87-90d9-a690d097cb95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>93c14448-ddee-47eb-9063-a15dbb573678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>3753e1f7-3b59-4e72-9b5e-78fec5af45e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Benedicta Company Name' or . = ' Benedicta Company Name')]</value>
      <webElementGuid>657fbf60-d5ac-440c-8457-074941f45bd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
