<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Archive</name>
   <tag></tag>
   <elementGuidId>ef0c2eb9-ed06-4bde-9146-1ccd4ccb7c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-danger.px-4.py-2.mx-3.fs12.my-2.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ba5caec-3790-41f7-9764-eb0b8b0a88b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-danger px-4 py-2 mx-3 fs12 my-2 ng-star-inserted</value>
      <webElementGuid>d7f9f338-bef2-4655-b25d-2fb71ce58a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Archive</value>
      <webElementGuid>141b184c-6356-440c-acb0-b0650548aa6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/modal-container[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog sm-modal&quot;]/div[@class=&quot;modal-content&quot;]/app-delete-modal[1]/div[@class=&quot;modal-footer border-0 justify-content-center flex-column flex-md-row btn-group ng-star-inserted&quot;]/button[@class=&quot;btn-danger px-4 py-2 mx-3 fs12 my-2 ng-star-inserted&quot;]</value>
      <webElementGuid>b5227311-b573-4687-94ec-42f99ae496a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>bed652fa-1898-44c7-9a56-17bb89a14f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to archive?'])[1]/following::button[2]</value>
      <webElementGuid>cc02a7a1-b09f-425a-af47-0dbef55b149d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Archive']/parent::*</value>
      <webElementGuid>01c303df-2323-46a8-b78a-396682247ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>fe7a7840-6aef-4c4c-a964-564238ef1f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Archive' or . = 'Archive')]</value>
      <webElementGuid>06bbf76b-5c93-4232-860a-37617605151a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
