<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Active_btn-outline</name>
   <tag></tag>
   <elementGuidId>a829f751-f596-44b1-96fb-d92c2be9526a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-equipment']/app-equipment/div/div/div/div/table/tbody/tr[5]/td[6]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2919bc99-7299-4595-8ea7-a19edac9e4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-outline</value>
      <webElementGuid>191abc24-7063-4cd0-b5c8-a88b864f5491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-equipment&quot;)/app-equipment[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;primary-table m-3&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table mb-0&quot;]/tbody[@class=&quot;ng-star-inserted&quot;]/tr[@class=&quot;c-pointer ng-star-inserted&quot;]/td[@class=&quot;text-center mw-100&quot;]/button[@class=&quot;btn-outline&quot;]</value>
      <webElementGuid>994a75ae-aea9-42ca-ac96-d41e6158719d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-equipment']/app-equipment/div/div/div/div/table/tbody/tr[5]/td[6]/button[2]</value>
      <webElementGuid>bd6d450f-376e-4e0e-ac30-7764a504cd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[5]/following::button[2]</value>
      <webElementGuid>8cc40946-3738-47a9-97dc-09e98df1c807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='---'])[5]/following::button[2]</value>
      <webElementGuid>7d6c1899-03e3-45c8-80f9-56649444a32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dfnjfks'])[1]/preceding::button[1]</value>
      <webElementGuid>65e27ae4-2e2c-4969-8f5d-15d45588f216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle'])[3]/preceding::button[1]</value>
      <webElementGuid>e27dffb6-78cb-4f14-a191-624315adc47c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[6]/button[2]</value>
      <webElementGuid>73532a9b-31e8-436e-b36a-4743ed90b13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-equipment']/app-equipment/div/div/div/div/table/tbody/tr[3]/td[6]/button</value>
      <webElementGuid>e0e143ba-0cb5-4eec-8b95-8dd822b53782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[4]/following::button[1]</value>
      <webElementGuid>3aaae42b-fcfa-4f3f-8f8c-126ce7502da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jhddhm'])[1]/following::button[1]</value>
      <webElementGuid>7eb5f4d9-e673-4341-a6da-cac13e7746f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Num'])[1]/preceding::button[2]</value>
      <webElementGuid>5d21a65c-044e-4089-981c-983f8c60a0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unpowered Equipment'])[2]/preceding::button[2]</value>
      <webElementGuid>b2729276-bb70-43a8-9875-34dff931e6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/button</value>
      <webElementGuid>bfe2486a-f8db-43bd-b361-c89f85303fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-team']/div/div/div/div/table/tbody/tr[2]/td[7]/button</value>
      <webElementGuid>b539e77e-bd88-4b1c-bae4-007e60c84c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[8]/following::button[1]</value>
      <webElementGuid>939b6a94-b9a0-49fd-a543-36c26cc445d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Season date'])[1]/following::button[1]</value>
      <webElementGuid>2a4235c8-439d-4fab-a821-0107791f6d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='djk vnkjsfhvkbhj'])[1]/preceding::button[2]</value>
      <webElementGuid>fbda37ac-285d-45e0-9555-34e987d1ff1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[9]/preceding::button[2]</value>
      <webElementGuid>d06ed229-0d6a-4b04-afb9-0a15b1f3c7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]/button</value>
      <webElementGuid>a098ce8a-d042-43ca-a468-f90c94538d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-team']/div/div/div/div/table/tbody/tr/td[7]/button[2]</value>
      <webElementGuid>1950ec6d-4475-420d-9d61-2dfc306c04fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[8]/following::button[2]</value>
      <webElementGuid>fb3bd5a8-0c15-49ff-afa8-383cfc7316c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaniiiiii Vv'])[1]/following::button[2]</value>
      <webElementGuid>140cbdbb-f071-43e7-b85a-677ef5489ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ncxv kjvjkvnjd'])[1]/preceding::button[1]</value>
      <webElementGuid>1b806078-387a-4961-84bd-ece289ca4208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[9]/preceding::button[1]</value>
      <webElementGuid>018c082f-ba74-4b08-90fa-c586fbd893c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/button[2]</value>
      <webElementGuid>477fed29-df85-43da-b74a-a11dbe328bb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
