<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Primary Role</name>
   <tag></tag>
   <elementGuidId>b12e915c-c0cc-4423-8889-214edc7b2a4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='teamMemberForm']/div/div[2]/angular2-multiselect/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>angular2-multiselect.custom-dropdown.form-control.mb-3.ng-untouched.ng-pristine.ng-valid > div.cuppa-dropdown > div.selected-list > div.c-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e4ad9429-847c-4bb2-96cc-63b0e38fcccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-btn</value>
      <webElementGuid>2d42fd78-2bae-4e8d-aae9-847ccb0d42c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1e1eff93-3ffb-4fc5-a4f9-e71ba8f2b27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Primary Role</value>
      <webElementGuid>dd662cc9-82f9-4ea9-8125-7e65a681719a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teamMemberForm&quot;)/div[@class=&quot;row align-items-start justify-content-center&quot;]/div[@class=&quot;col-12 col-md-6 pe-md-4 mb-3&quot;]/angular2-multiselect[@class=&quot;custom-dropdown form-control mb-3 ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;cuppa-dropdown&quot;]/div[@class=&quot;selected-list&quot;]/div[@class=&quot;c-btn&quot;]</value>
      <webElementGuid>f1559bd1-4ab0-4d75-8ccd-b71720ef7a4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='teamMemberForm']/div/div[2]/angular2-multiselect/div/div/div</value>
      <webElementGuid>651d6a9d-f312-4c5e-97b3-7624acd30887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip Code'])[1]/following::div[3]</value>
      <webElementGuid>aa297c14-2bfd-4ccd-86af-43feba36906f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::div[5]</value>
      <webElementGuid>b0a63b96-bcc5-440d-9217-b459a8e5703d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Members'])[2]/preceding::div[5]</value>
      <webElementGuid>0e68d061-dc10-4cce-922b-33fe9a50a591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/angular2-multiselect/div/div/div</value>
      <webElementGuid>b51961b2-1059-4264-952d-5e5ead7da6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Primary Role' or . = 'Primary Role')]</value>
      <webElementGuid>abaf945d-235d-480c-93f5-ca1c1ea9eee5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
