<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Filter Status</name>
   <tag></tag>
   <elementGuidId>6c04c0af-ccf0-45eb-9803-23e28d0503fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.c-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-equipment']/app-equipment/div/div/div/ul/li[2]/app-multi-select/angular2-multiselect/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ddc7ce0-6395-4ead-a577-ce01bafb9adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-btn</value>
      <webElementGuid>f6ee8862-80d4-4994-8cdf-7f8a6033c9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ce857d9a-cb5e-4f47-9c74-a59a660c4f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter Status</value>
      <webElementGuid>f2586946-0b09-4f26-8b6e-c796b162f60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-equipment&quot;)/app-equipment[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;primary-table m-3&quot;]/ul[@class=&quot;list-inline mb-0 px-3 py-4&quot;]/li[@class=&quot;list-inline-item mb-3&quot;]/app-multi-select[1]/angular2-multiselect[@class=&quot;custom-dropdown custom-dropdown-sm filter-select form-control position-relative ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;cuppa-dropdown&quot;]/div[@class=&quot;selected-list&quot;]/div[@class=&quot;c-btn&quot;]</value>
      <webElementGuid>54fd04c7-be00-4db9-a63c-919af5bdb50d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-equipment']/app-equipment/div/div/div/ul/li[2]/app-multi-select/angular2-multiselect/div/div/div</value>
      <webElementGuid>f99ac408-ccb7-403e-ba4b-01b8ecd0dadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment Groups'])[1]/following::div[10]</value>
      <webElementGuid>95f4ed2e-7a04-4904-82cf-1686f0184a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment'])[3]/following::div[10]</value>
      <webElementGuid>3e16e022-7f5d-49d9-a77f-6099467f75df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/preceding::div[3]</value>
      <webElementGuid>ea05dccc-83bb-4663-b5af-eabd9b41681f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//angular2-multiselect/div/div/div</value>
      <webElementGuid>e4af89d9-74d2-4180-bdc8-50887fee23bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Filter Status' or . = 'Filter Status')]</value>
      <webElementGuid>806da1f4-2b7b-4eba-afdf-012f4eba0d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-group']/app-equipment-group/div/div/div/ul/li[2]/app-multi-select/angular2-multiselect/div/div/div</value>
      <webElementGuid>04132e78-c277-4afb-8b0d-b473b42a93e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='page'])[7]/following::div[9]</value>
      <webElementGuid>e7a9957b-bafa-4c39-8b82-c1126a1e5b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[2]/preceding::div[3]</value>
      <webElementGuid>c9191d7a-b6e3-4c68-8342-820e808d60ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-equipment-group/div/div/div/ul/li[2]/app-multi-select/angular2-multiselect/div/div/div</value>
      <webElementGuid>5b4324fc-ce26-4800-861c-9cc6d66de956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-team']/div/div/div/ul/li[2]/app-multi-select/angular2-multiselect/div/div/div</value>
      <webElementGuid>a846998f-b42f-4a6b-95a9-4d12040fb248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='page'])[6]/following::div[9]</value>
      <webElementGuid>b0c7407a-93ed-4f7c-a8ec-cf6cc202e585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[2]/app-multi-select/angular2-multiselect/div/div/div</value>
      <webElementGuid>0c0beba1-ac77-49c7-9705-1eb247e9c8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-crews']/div/div/div/ul/li[2]/app-multi-select/angular2-multiselect/div/div/div</value>
      <webElementGuid>b65a5fe7-5499-43ba-add5-27ae9cf91334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Members'])[1]/following::div[10]</value>
      <webElementGuid>3146a231-150f-4e3c-b0a6-3b90d468e356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crews'])[3]/following::div[10]</value>
      <webElementGuid>a8536adc-eca2-43e1-b3a0-0b2698d4e109</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
