<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Equipment Type  Other  Powered Equipment  Unpowered Equipment  Battery  Vehicle  Other NameSerialSizeWeight (lbs)</name>
   <tag></tag>
   <elementGuidId>a05dc5aa-80df-4f84-a683-6da8168ef14d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='equipmentForm']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-12.col-md-6.pe-4.border-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11cf823d-a4a3-4ca8-839d-117ee5ad607b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-12 col-md-6 pe-4 border-right</value>
      <webElementGuid>09df5340-5f56-478c-961a-56445f5344a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Equipment Type*  Other  Powered Equipment  Unpowered Equipment  Battery  Vehicle  Other Name*SerialSizeWeight (lbs)</value>
      <webElementGuid>a2429305-e690-4757-a63b-01444ed1d26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;equipmentForm&quot;)/div[@class=&quot;row align-items-start justify-content-center&quot;]/div[@class=&quot;col-12 col-md-6 pe-4 border-right&quot;]</value>
      <webElementGuid>83d5cebd-69e3-4902-99a8-50ae5028cd13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='equipmentForm']/div/div</value>
      <webElementGuid>4cb1b986-3120-484f-8a26-b2b1705d39b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Require Maintenance'])[2]/following::div[3]</value>
      <webElementGuid>d3608295-c061-440a-b7f0-d70a4fe1ff05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archived'])[12]/following::div[3]</value>
      <webElementGuid>843e151b-d2b1-440d-8832-4137c64eb490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>67136024-8997-4dd6-8735-e6786aa8ea1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Equipment Type*  Other  Powered Equipment  Unpowered Equipment  Battery  Vehicle  Other Name*SerialSizeWeight (lbs)' or . = ' Equipment Type*  Other  Powered Equipment  Unpowered Equipment  Battery  Vehicle  Other Name*SerialSizeWeight (lbs)')]</value>
      <webElementGuid>bf2bac2d-c5c6-4a16-9a5d-3f5b46846db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
