<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Equipment Group NameNotes</name>
   <tag></tag>
   <elementGuidId>2b52f635-a076-4298-a941-fa070fd98333</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-12.col-md-6.pe-4.border-right.textarea-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='equipmentGroupForm']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2cef8979-2af4-4b2f-a6b6-2495d32f345b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-12 col-md-6 pe-4 border-right textarea-md</value>
      <webElementGuid>c0274ef4-55d5-4b88-ac3f-74401c363207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Equipment Group Name*Notes</value>
      <webElementGuid>fab5efa6-4dfe-4931-9b86-ba14a5043097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;equipmentGroupForm&quot;)/div[@class=&quot;row align-items-start justify-content-center&quot;]/div[@class=&quot;col-12 col-md-6 pe-4 border-right textarea-md&quot;]</value>
      <webElementGuid>b47e5338-0c9d-4f25-8aff-3438c835a017</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='equipmentGroupForm']/div/div</value>
      <webElementGuid>f3c6e80e-1009-48e1-babe-b2d97873bf13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archived'])[15]/following::div[3]</value>
      <webElementGuid>67dcb2e8-1660-4bce-9969-ddfc40f58db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[4]/following::div[3]</value>
      <webElementGuid>06f4a20c-cbd5-4273-8b42-16f87c03bca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>821f91ff-fe32-4bee-80f2-c50612bffbf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Equipment Group Name*Notes' or . = 'Equipment Group Name*Notes')]</value>
      <webElementGuid>e8596569-410f-4b72-aab5-5ee493897c3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
