<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vaniiiiii Vvhjhuk hgjhu</name>
   <tag></tag>
   <elementGuidId>a40f08cd-4444-4168-ab30-36a87962a686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='crewForm']/div/div/angular2-multiselect/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.c-list.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e1282892-73ef-4c43-a65c-7448923fb5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-list ng-star-inserted</value>
      <webElementGuid>06c89296-d563-4c55-aeeb-10b9e2b9ea79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vaniiiiii Vvhjhuk hgjhu</value>
      <webElementGuid>009a6fd4-ea82-432b-bed7-17956223c9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crewForm&quot;)/div[@class=&quot;row align-items-start justify-content-center&quot;]/div[@class=&quot;col-12 col-md-6 pe-md-4 mb-3&quot;]/angular2-multiselect[@class=&quot;custom-dropdown form-control mb-4 ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;cuppa-dropdown&quot;]/div[@class=&quot;selected-list&quot;]/div[@class=&quot;c-btn&quot;]/div[@class=&quot;c-list ng-star-inserted&quot;]</value>
      <webElementGuid>558c176f-c5f8-4b8e-aac4-6355f94882a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='crewForm']/div/div/angular2-multiselect/div/div/div/div</value>
      <webElementGuid>319d1e43-3094-410a-9a73-6ff9f7fea51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crew Name*'])[1]/following::div[4]</value>
      <webElementGuid>1dfe9b4b-c9b1-45cf-9eb1-f25594099200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archived'])[10]/following::div[8]</value>
      <webElementGuid>9eb21bc6-8ce3-4bfa-8175-4782353d883b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/angular2-multiselect/div/div/div/div</value>
      <webElementGuid>3cbff5f0-cee8-401d-b674-99e0dee175f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Vaniiiiii Vvhjhuk hgjhu' or . = 'Vaniiiiii Vvhjhuk hgjhu')]</value>
      <webElementGuid>f3a5fe50-056b-44e3-9e86-2f0a83eff6eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
