<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Company Name_lnr lnr-chevron-down</name>
   <tag></tag>
   <elementGuidId>029a0626-5c95-4d1e-98cf-45c3484e5234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-equipment']/app-equipment/div/div/div/div/table/tbody/tr[2]/td[6]/button[2]/em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>528b6766-24a2-43a5-8282-93fa91b82d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lnr lnr-trash ng-star-inserted</value>
      <webElementGuid>f8f606d0-0d04-4e64-827f-ea95737a9574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-equipment&quot;)/app-equipment[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;primary-table m-3&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table mb-0&quot;]/tbody[@class=&quot;ng-star-inserted&quot;]/tr[@class=&quot;c-pointer ng-star-inserted&quot;]/td[@class=&quot;text-center mw-100&quot;]/button[@class=&quot;btn-outline&quot;]/em[@class=&quot;lnr lnr-trash ng-star-inserted&quot;]</value>
      <webElementGuid>0368dcd3-591b-4cd5-97e0-a102287dc4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d57deb0f-91f0-44f4-be5a-daaca44fd289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-equipment']/app-equipment/div/div/div/div/table/tbody/tr[2]/td[6]/button[2]/em</value>
      <webElementGuid>6d386120-bdef-40eb-87aa-19fcd134b551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/button[2]/em</value>
      <webElementGuid>f4ae4c6c-4538-43a0-b3c9-f7631b175734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/app-input[2]/div/div/em</value>
      <webElementGuid>8f53a94d-22ce-4cdf-b71c-65ad4faed035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>97d8cee1-d582-4035-a6e3-68b8ef1198a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='equipmentForm']/div/div/app-select/div/button/em</value>
      <webElementGuid>afa5c8ee-195f-4e10-aefe-c3ad5d0096d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-select/div/button/em</value>
      <webElementGuid>d8818e62-3345-4056-b6ec-d0eadda51e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-group']/app-equipment-group/div/div/div/div/table/tbody/tr[3]/td[5]/button[2]/em</value>
      <webElementGuid>9b993dd7-6b37-447f-b5e6-b5e17cc1a690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/button[2]/em</value>
      <webElementGuid>6cccb052-561a-48f1-99d9-066ef555585f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-team']/div/div/div/div/table/tbody/tr/td[7]/button/em</value>
      <webElementGuid>8053a88c-a9e0-4691-82ea-aae3cd377344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/button/em</value>
      <webElementGuid>53600b47-f498-45a6-b398-3adcaf036f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-crews']/div/div/div/div/table/tbody/tr/td[6]/button/em</value>
      <webElementGuid>77a88fbb-e774-4976-b51c-fec9085a2569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/button/em</value>
      <webElementGuid>eeefe76e-366b-44aa-9e33-3611849afd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-crews']/div/div/div/div/table/tbody/tr[6]/td[6]/button[2]/em</value>
      <webElementGuid>5d887513-6404-49dc-9708-a93a243cf2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[6]/button[2]/em</value>
      <webElementGuid>0eec5be7-7825-4788-9cd5-a880d91c6138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='changePasswordForm']/div/app-input[2]/div/div/em</value>
      <webElementGuid>fa1b83e6-474b-4ae7-898e-fd11b2a6c839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-input[2]/div/div/em</value>
      <webElementGuid>341d452a-cdeb-4fda-8cad-514388944fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='changePasswordForm']/div/app-password-criteria-input/div/div/em</value>
      <webElementGuid>3b5efc7d-c6d6-4dc9-b692-3b3232704a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-password-criteria-input/div/div/em</value>
      <webElementGuid>0c8b44ba-bf25-47ed-a93f-7f714245f197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='changePasswordForm']/div/app-input/div/div/em</value>
      <webElementGuid>ef81fb82-ab78-4f3f-8e04-a674383567e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-input/div/div/em</value>
      <webElementGuid>68b8c041-9478-4e2d-9b4b-c48942cf3ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/em</value>
      <webElementGuid>6c67912b-c2cc-4484-9418-90ba0cae3a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='changePasswordForm']/div[2]/button[2]/em</value>
      <webElementGuid>686b0c9b-423e-4960-a254-e4fbf7465a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/em</value>
      <webElementGuid>3838f985-ab7c-4592-860d-a6cfbf5ff4f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
