<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>8dd86c98-c163-47b2-915e-66ff004d8eb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Crews']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Crews&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fdf05a03-d9c4-408e-b839-be928aa82529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../assets/icons/sidemenu-icons/crew-icon.svg</value>
      <webElementGuid>3cc49720-e8b4-4e45-b3eb-ee79d78f3822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Crews</value>
      <webElementGuid>7f06bce6-fdce-466a-ac35-5d0b6dc5a102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-app-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;admin-layout&quot;]/aside[@class=&quot;own-sidemenu-main show&quot;]/app-sidemenu[1]/aside[@class=&quot;sidemenu-main menu-opened&quot;]/ul[@class=&quot;list-group&quot;]/li[@class=&quot;list-group-item&quot;]/a[1]/div[@class=&quot;menu-icon&quot;]/span[@class=&quot;active-img&quot;]/img[1]</value>
      <webElementGuid>9cfae6fc-1378-4e6c-b3d6-0a01012b42c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Crews']</value>
      <webElementGuid>8b98bff0-b75b-4311-9036-98efe0442461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/div/span/img</value>
      <webElementGuid>e68a75db-7c62-49c8-9481-d660ac742bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../assets/icons/sidemenu-icons/crew-icon.svg' and @alt = 'Crews']</value>
      <webElementGuid>22411a5e-d201-4633-95a4-2dcfb11ea1bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
