<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Active_image-fluid ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>dc4844c9-c570-4c7d-aedb-e7688848b405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-equipment']/app-equipment/div/div/div/div/table/tbody/tr[2]/td[6]/button[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2fc26727-fa0c-4f94-8e51-0c45b01774a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../assets/icons/archive-file.svg</value>
      <webElementGuid>e205fee0-4e32-4a6b-be1b-8738a8398619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>archive-file</value>
      <webElementGuid>71c8bbee-b27c-4b6b-bda9-6a10089ad61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-fluid ng-star-inserted</value>
      <webElementGuid>c8113190-fa80-4bcb-a0ae-c51cd27d5399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-equipment&quot;)/app-equipment[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;primary-table m-3&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table mb-0&quot;]/tbody[@class=&quot;ng-star-inserted&quot;]/tr[@class=&quot;c-pointer ng-star-inserted&quot;]/td[@class=&quot;text-center mw-100&quot;]/button[@class=&quot;btn-outline&quot;]/img[@class=&quot;image-fluid ng-star-inserted&quot;]</value>
      <webElementGuid>75671dc2-0194-48c9-9cc8-65b5c9e9886b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-equipment']/app-equipment/div/div/div/div/table/tbody/tr[2]/td[6]/button[2]/img</value>
      <webElementGuid>aac9fb5d-7425-4e8a-9019-93ccc47978a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='archive-file'])[2]</value>
      <webElementGuid>1cb009a5-d7ca-4097-ac4c-dbdb5c847c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/button[2]/img</value>
      <webElementGuid>68e75e74-af25-4299-a509-90df4ed9924b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../../assets/icons/archive-file.svg' and @alt = 'archive-file']</value>
      <webElementGuid>a68dc132-de44-4f31-b321-1e685d90502c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
