<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Archived_Equipment Group Name</name>
   <tag></tag>
   <elementGuidId>51007149-12c7-49fb-9289-48af3dec4f74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Equipment Group Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a1885e2-6504-4cea-99ba-26e4cdf2f7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>labelName</value>
      <webElementGuid>24957493-00fe-4bcd-83a5-88ca8dbb2c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>edff26d3-d924-48d5-8cc6-e28a52e0ec75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd6a6fc5-ff94-4faa-a9b8-367488a072d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Equipment Group Name</value>
      <webElementGuid>b85b3ae7-925d-4889-807d-0a01719ca9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Equipment Group Name&quot;)</value>
      <webElementGuid>d9b5c127-096a-42f4-981b-4071b3b4dca3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Equipment Group Name']</value>
      <webElementGuid>a153af53-ea56-464f-8972-2fc07ffb0a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='equipmentGroupForm']/div/div/app-input/div/input</value>
      <webElementGuid>afce3811-11e5-4a02-9c2b-55cd242a05ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-input/div/input</value>
      <webElementGuid>3b2d6956-d10e-4577-b26b-235742d18902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'labelName' and @type = 'text' and @id = 'Equipment Group Name']</value>
      <webElementGuid>18fc207d-6242-4778-b95c-a0f548c698c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
