<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maximum of 20 Characters_Confirm Password</name>
   <tag></tag>
   <elementGuidId>7b9286fe-3274-4745-8337-9c370951d0a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Confirm Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52f100df-94fd-4dcb-95f1-0c955782e8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>labelName</value>
      <webElementGuid>45143746-7be0-4f52-9485-1d181ce56d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-invalid ng-star-inserted ng-dirty</value>
      <webElementGuid>a4ba3e89-4675-4ce4-85f0-22df2f51afc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>19d48dd4-eed5-4b82-8fc7-00ed4cc31898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>84980cc5-3789-4158-a277-c9eb67794c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Confirm Password&quot;)</value>
      <webElementGuid>8a70f99e-3cb2-42b3-a472-1ffda8fb854e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Confirm Password']</value>
      <webElementGuid>86d34103-91a2-4d5d-8529-1d08905f5e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='changePasswordForm']/div/app-input[2]/div/input</value>
      <webElementGuid>17eece00-32c2-43e8-930d-257cec28d8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-input[2]/div/input</value>
      <webElementGuid>ba9bf67a-2913-471f-accb-1a71e6d3aa7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'labelName' and @type = 'password' and @id = 'Confirm Password']</value>
      <webElementGuid>b07bc873-ee0b-4555-ac37-99b261aa293c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'labelName' and @type = 'text' and @id = 'Confirm Password']</value>
      <webElementGuid>d2797932-d9d5-4780-957c-ee56ffd85caf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
