<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Key Specialties_Notes</name>
   <tag></tag>
   <elementGuidId>07dc4fe8-1bf3-4b21-b701-f74f8f7bb8c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Notes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Notes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a67fafdd-39a5-410a-ae7e-b2b33351f965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>labelName</value>
      <webElementGuid>becb5462-7785-4edb-b68d-94144d9fb40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>f6d81d62-ac56-4d9f-b9c3-9d9e4541859e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1db28e8f-dcd7-4b8e-8a3c-12eb77189632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>5c01aa06-09f4-47c1-b283-39bdbb2c568e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Notes&quot;)</value>
      <webElementGuid>53e9d8a1-63f3-460e-9063-763108ae24c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Notes']</value>
      <webElementGuid>f6fa6587-88b9-4c0b-9b16-0e8469b77bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='crewForm']/div/div[2]/div/app-input/div/input</value>
      <webElementGuid>733659c4-9f04-400b-95ab-f25804b69d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/app-input/div/input</value>
      <webElementGuid>20e0d74e-2e8e-43b5-bbe7-d0da141f0a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'labelName' and @type = 'text' and @id = 'Notes']</value>
      <webElementGuid>46787bab-65d5-46d4-9d95-25d52bf9219f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
