<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Inactive</name>
   <tag></tag>
   <elementGuidId>981a7c35-b208-4815-a8c3-96df8ef4052b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@value='1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>97093b2e-c6f7-405b-9c62-741d11ae8a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item fs12 p-2 pl-3 ng-star-inserted</value>
      <webElementGuid>04a3484b-5b60-47aa-906b-6184b89036cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>36b3ada7-5f30-4b30-9181-abb43ad8a252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>70183f7c-fe5a-4c4b-ab56-079aba4cf577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Inactive </value>
      <webElementGuid>626b5295-f1ae-4701-8ee7-7d8ad48a2995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-1 modal-open&quot;]/modal-container[@class=&quot;modal fade show&quot;]/div[@class=&quot;md-modal modal-dialog sm-modal&quot;]/div[@class=&quot;modal-content&quot;]/app-crew-modal[1]/div[1]/div[@class=&quot;modal-header border-bottom-0 pb-0 px-4&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;filter-select position-relative&quot;]/ul[@class=&quot;dropdown-menu p-0 c-pointer w-100 show&quot;]/li[@class=&quot;dropdown-item fs12 p-2 pl-3 ng-star-inserted&quot;]</value>
      <webElementGuid>363809f3-bf59-4236-85af-7354cc9f68a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@value='1']</value>
      <webElementGuid>3ed799de-87eb-4d09-be21-6e460e7e5dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[14]/following::li[1]</value>
      <webElementGuid>41638dc0-aa75-40ac-9086-181a8d625bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[13]/following::li[2]</value>
      <webElementGuid>56162a9a-e798-423a-847f-45450e86c895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archived'])[12]/preceding::li[1]</value>
      <webElementGuid>371e9983-ee02-41cc-8f15-25b0beb8e4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crew Name*'])[1]/preceding::li[2]</value>
      <webElementGuid>64a8e0fd-f212-4ee2-8276-8e50df6248bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-crew-modal/div/div/div/div/ul/li[2]</value>
      <webElementGuid>28e20546-b9fc-4982-bc14-fa1d131a38bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = ' Inactive ' or . = ' Inactive ')]</value>
      <webElementGuid>ace7fbc9-0da8-4489-ba24-e9e6ebbdff0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
