<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_No Data Found</name>
   <tag></tag>
   <elementGuidId>550b3dc8-3954-4757-be7a-b4ad44962af3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-center.fs18.fw-600.p-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-equipment']/app-equipment/div/div/div/div/table/tbody/tr/td/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>266a41b5-9388-4690-a709-badd438eb828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center fs18 fw-600 p-5</value>
      <webElementGuid>e00a05b7-bfea-4046-9148-945f7959769c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> No Data Found </value>
      <webElementGuid>1704754e-a919-45ad-b7ad-2552119a8d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-equipment&quot;)/app-equipment[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;primary-table m-3&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table mb-0&quot;]/tbody[@class=&quot;ng-star-inserted&quot;]/tr[1]/td[1]/p[@class=&quot;text-center fs18 fw-600 p-5&quot;]</value>
      <webElementGuid>62e5d6b6-48a3-4798-aa11-99e26e12d8e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-equipment']/app-equipment/div/div/div/div/table/tbody/tr/td/p</value>
      <webElementGuid>eafe1bd7-a81a-4b48-afee-1feebafc1ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::p[1]</value>
      <webElementGuid>0131ec03-7989-4b00-888d-d6b32f319f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::p[1]</value>
      <webElementGuid>6534ada6-0bdc-4ab6-9db1-5c43decc718c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Status'])[2]/preceding::p[1]</value>
      <webElementGuid>f84138ae-e545-4b36-8060-5d1691089c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[2]/preceding::p[1]</value>
      <webElementGuid>8a9d39ef-07bc-4993-ad9a-d4f3d89dc9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No Data Found']/parent::*</value>
      <webElementGuid>505d3884-4565-4529-875e-825e70a3cd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>8895da0f-5a6a-4209-8399-d902798fe9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = ' No Data Found ' or . = ' No Data Found ')]</value>
      <webElementGuid>765cea1a-53fa-4765-80dd-681a170b2583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-group']/app-equipment-group/div/div/div/div/table/tbody/tr/td/p</value>
      <webElementGuid>9f4b09f2-a958-4420-93bc-97103b1707a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/following::p[1]</value>
      <webElementGuid>9934def3-245a-45b5-8efe-fa97ede64157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::p[1]</value>
      <webElementGuid>adce4e07-1d02-43a6-84d3-c99e7ae2ed36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-equipment-group/div/div/div/div/table/tbody/tr/td/p</value>
      <webElementGuid>778be2a9-8c73-482d-b659-cab4b20f5c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-team']/div/div/div/div/table/tbody/tr/td/p</value>
      <webElementGuid>480f48a5-0fbd-4301-b7af-8cf3198b4229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/table/tbody/tr/td/p</value>
      <webElementGuid>1546cfea-27e8-4410-9b05-34477ee025f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'No Data Found' or . = 'No Data Found')]</value>
      <webElementGuid>31c86525-cc02-4e3c-a104-0f713d87df66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-crews']/div/div/div/div/table/tbody/tr/td/p</value>
      <webElementGuid>72f70495-0a63-4b62-8770-0e27f20cca44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
