<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Filter Status</name>
   <tag></tag>
   <elementGuidId>e33a08b0-f6c7-427f-8150-053b438c2eeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-team']/div/div/div/ul/li[2]/app-multi-select/angular2-multiselect/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-team > div.row > div.col-12 > div.primary-table.m-3 > ul.list-inline.mb-0.px-3.py-4 > li.list-inline-item.mb-2.mb-md-0 > app-multi-select > angular2-multiselect.custom-dropdown.custom-dropdown-sm.filter-select.form-control.position-relative.ng-untouched.ng-pristine.ng-valid > div.cuppa-dropdown > div.selected-list > div.c-btn > span.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dd85940b-1fb9-4b54-8627-5a760d675577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>25021992-58a6-4bb6-a710-11069571ae65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter Status</value>
      <webElementGuid>f73c7bca-1863-46f8-8205-c9f8286a135b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-team&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;primary-table m-3&quot;]/ul[@class=&quot;list-inline mb-0 px-3 py-4&quot;]/li[@class=&quot;list-inline-item mb-2 mb-md-0&quot;]/app-multi-select[1]/angular2-multiselect[@class=&quot;custom-dropdown custom-dropdown-sm filter-select form-control position-relative ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;cuppa-dropdown&quot;]/div[@class=&quot;selected-list&quot;]/div[@class=&quot;c-btn&quot;]/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>235fa44c-eac3-4910-b120-bec301269194</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-team']/div/div/div/ul/li[2]/app-multi-select/angular2-multiselect/div/div/div/span</value>
      <webElementGuid>f7fc62c7-1f84-4bea-a87f-6649c72ed1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='page'])[6]/following::span[3]</value>
      <webElementGuid>a553c4d9-decd-46ed-99fa-50764eb14c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[2]/preceding::span[2]</value>
      <webElementGuid>7134bd3c-738e-4398-8b0e-bbe3c61557a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UnSelect All'])[2]/preceding::span[3]</value>
      <webElementGuid>d42ec032-f555-47a3-ada3-840403ec61a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[2]/app-multi-select/angular2-multiselect/div/div/div/span</value>
      <webElementGuid>4758343b-d6e4-4df9-9649-27dcd34f2e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Filter Status' or . = 'Filter Status')]</value>
      <webElementGuid>7f9020fc-0cbf-4d2a-b7a6-c40f250975e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
